services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Server=db;Port=5080;Database=RecipesDB;Username=postgres;Password=postgres;

  db:
    image: postgres:14
    ports:
      - "5080:5080"
    environment:
      PGPORT: 5080
      POSTGRES_DB: RecipesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d RecipesDB'"]
      interval: 5s
      timeout: 3s
      retries: 5