name: Recipes .NET

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Recipes/**
  pull_request:
    branches:
      - main
    paths:
      - Recipes/**

jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci.yaml
    with:
      solution-directory: Recipes
